### ISSUE TITLE
Array size mismatch: SMPL-Scene-Viewer/smpl/smpl.py, line 161

### ISSUE THREAD

**Issue by guidodumont** [climbingdaily/vis_lidar_human_scene#1]
Hi, I tried running your visualizer with smpl_sample.pkl, following the README. However, I encounter a runtime error when opening the file:

File "SMPL-Scene-Viewer/smpl/smpl.py", line 161, in forward
    v_posed = v_shaped + torch.matmul(posedirs, lrotmin[:, :, None]).view(-1, 6890, 3)
RuntimeError: The size of tensor a (30720) must match the size of tensor b (1024) at non-singleton dimension 0

The error occurs due to the mismatch in size during addition:
- *posedirs:* torch.Size([1024, 20670, 207])
- *lrotmin[:, :, None]:* torch.Size([1024, 207])
- *torch.matmul(posedirs, lrotmin[:, :, None]):* torch.Size([1024, 20670, 1]), cannot be reshaped in torch.Size([30720, 6890, 3])
- *v_shaped:* torch.Size([30720, 6890, 3])

Can you provide me any information on how I can fix this error?
Is it possible that the error occurs due to the V1.1.0 release of the SMPL model? (I had to rename the files in order to make them compatible)

Many thanks for considering my request.

Kind regards,

Guido

**Comment by climbingdaily** [comment]
Hi Guido. Yes, this problem is caused by the SMPL model's version. You should use the V1.0.0 version. Because `v_shaped`'s sizes are different.
```
v_shaped.shape
torch.Size([1024, 6890, 3])
```

**Comment by guidodumont** [comment]
Thank you very much, it works now!! Compliments for the fast response and nice visualization tool!
